src/web/app-pms.web/Controllers/DocumentController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using App_Pms.Web.Security;
using System.IO;
using Microsoft.AspNetCore.Mvc.Rendering;
using App_Pms.Web.DPWApiClient.Workflow.Entities;
using App_Pms.Web.DPWApiClient.Workflow.Entities.Input;
using Microsoft.Extensions.Options;
using App_Pms.Web.DPWApiClient.Workflow.Manager;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Authorization;

namespace App_Pms.Web.Controllers
{
    [Authorize]
    public class DocumentController : Controller
    {
        private readonly IPInput _ipInput;
        private readonly DepartmentInput _departmentsInput;
        private readonly DocumentaryTypologyInput _documentaryTypologyInput;
        private readonly CreationReasonInput _creationReasonInput;
        private readonly RetentionTimeInput _retentionTimeInput;
        private readonly StorageMediaInput _storageMediaInput;
        private readonly ReviewFrequencyInput _reviewFrequencyInput;
        private readonly ClassificationInput _classificationInput;
        private readonly WFDocumentCreateInput _wfDocumentCreateInput;
        private readonly WFDocumentSelectInput _wfDocumentSelectInput;
        private readonly WFDocumentSelectListDocsInput _wfDocumentSelectListDocsInput;
        private readonly WFDocumentSaveApproveRejectInput _wfDocumentSaveApproveRejectInput;
        private readonly WFDocumentDownloadInput _wfDocumentDownloadInput;
        private readonly WFDocumentTemplatesInput _wfDocumentTemplatesInput;
        private readonly WFDocumentAnnexedInput _wfDocumentAnnexedInput;
        private readonly WFDocumentReportMatrizRetencionesInput _wfDocumentReportMatrizRetencionesInput;
        private readonly WFDocumentReportListadoMaestroDocsInput _wfDocumentReportListadoMaestroDocsInput;
        private readonly WFDocumentReportListadoDocsObsoletosInput _wfDocumentReportListadoDocsObsoletosInput;
        private readonly LastStepInput _lastStepInput;
        private readonly string _strIP;

        public DocumentController(
                                  IOptions<IPInput> ipInput,
                                  IOptions<DepartmentInput> departmentsInput,
                                  IOptions<DocumentaryTypologyInput> documentaryTypologyInput,
                                  IOptions<CreationReasonInput> creationReasonInput,
                                  IOptions<RetentionTimeInput> retentionTimeInput,
                                  IOptions<StorageMediaInput> storageMediaInput,
                                  IOptions<ReviewFrequencyInput> reviewFrequencyInput,
                                  IOptions<ClassificationInput> classificationInput,
                                  IOptions<WFDocumentCreateInput> wfDocumentCreateInput,
                                  IOptions<WFDocumentSelectInput> wfDocumentSelectInput,
                                  IOptions<WFDocumentSelectListDocsInput> wfDocumentSelectListDocsInput,
                                  IOptions<WFDocumentSaveApproveRejectInput> wfDocumentSaveApproveRejectInput,
                                  IOptions<WFDocumentDownloadInput> wfDocumentDownloadInput,
                                  IOptions<WFDocumentTemplatesInput> wfDocumentTemplatesInput,
                                  IOptions<WFDocumentAnnexedInput> wfDocumentAnnexedInput,
                                  IOptions<WFDocumentReportMatrizRetencionesInput> wfDocumentReportMatrizRetencionesInput,
                                  IOptions<WFDocumentReportListadoMaestroDocsInput> wfDocumentReportListadoMaestroDocsInput,
                                  IOptions<WFDocumentReportListadoDocsObsoletosInput> wfDocumentReportListadoDocsObsoletosInput,
                                  IOptions<LastStepInput> lastStepInput
                                 )
        {
            _ipInput = ipInput.Value;
            _departmentsInput = departmentsInput.Value;
            _documentaryTypologyInput = documentaryTypologyInput.Value;
            _creationReasonInput = creationReasonInput.Value;
            _retentionTimeInput = retentionTimeInput.Value;
            _storageMediaInput = storageMediaInput.Value;
            _reviewFrequencyInput = reviewFrequencyInput.Value;
            _classificationInput = classificationInput.Value;
            _wfDocumentCreateInput = wfDocumentCreateInput.Value;
            _wfDocumentSelectInput = wfDocumentSelectInput.Value;
            _wfDocumentSelectListDocsInput = wfDocumentSelectListDocsInput.Value;
            _wfDocumentSaveApproveRejectInput = wfDocumentSaveApproveRejectInput.Value;
            _wfDocumentDownloadInput = wfDocumentDownloadInput.Value;
            _wfDocumentTemplatesInput = wfDocumentTemplatesInput.Value;
            _wfDocumentAnnexedInput = wfDocumentAnnexedInput.Value;
            _wfDocumentReportMatrizRetencionesInput = wfDocumentReportMatrizRetencionesInput.Value;
            _wfDocumentReportListadoMaestroDocsInput = wfDocumentReportListadoMaestroDocsInput.Value;
            _wfDocumentReportListadoDocsObsoletosInput = wfDocumentReportListadoDocsObsoletosInput.Value;
            _lastStepInput = lastStepInput.Value;

            _strIP = _ipInput.flag_url_dpw.Equals("0") ? _ipInput.url_dev : (_ipInput.flag_url_dpw.Equals("1") ? _ipInput.url_prd : string.Empty);
            
            _departmentsInput.url = _departmentsInput.url.Replace("{IP}", _strIP);
            _documentaryTypologyInput.url = _documentaryTypologyInput.url.Replace("{IP}", _strIP);
            _creationReasonInput.url = _creationReasonInput.url.Replace("{IP}", _strIP);
            _retentionTimeInput.url = _retentionTimeInput.url.Replace("{IP}", _strIP);
            _storageMediaInput.url = _storageMediaInput.url.Replace("{IP}", _strIP);
            _reviewFrequencyInput.url = _reviewFrequencyInput.url.Replace("{IP}", _strIP);
            _classificationInput.url = _classificationInput.url.Replace("{IP}", _strIP);
            _wfDocumentCreateInput.url = _wfDocumentCreateInput.url.Replace("{IP}", _strIP);
            _wfDocumentSelectInput.url = _wfDocumentSelectInput.url.Replace("{IP}", _strIP);
            _wfDocumentSelectListDocsInput.url = _wfDocumentSelectListDocsInput.url.Replace("{IP}", _strIP);
            _wfDocumentSaveApproveRejectInput.url = _wfDocumentSaveApproveRejectInput.url.Replace("{IP}", _strIP);
            _wfDocumentDownloadInput.url = _wfDocumentDownloadInput.url.Replace("{IP}", _strIP);
            _wfDocumentTemplatesInput.url = _wfDocumentTemplatesInput.url.Replace("{IP}", _strIP);
            _wfDocumentAnnexedInput.url = _wfDocumentAnnexedInput.url.Replace("{IP}", _strIP);
            _wfDocumentReportMatrizRetencionesInput.url = _wfDocumentReportMatrizRetencionesInput.url.Replace("{IP}", _strIP);
            _wfDocumentReportListadoMaestroDocsInput.url = _wfDocumentReportListadoMaestroDocsInput.url.Replace("{IP}", _strIP);
            _wfDocumentReportListadoDocsObsoletosInput.url = _wfDocumentReportListadoDocsObsoletosInput.url.Replace("{IP}", _strIP);
        }

        // GET: Document
        [SessionTimeout]
        public async Task<IActionResult> Index()
        {
            try
            {
                var _listadoDocs = await ListDocsQueueAsync();
                ViewData["url_download"] = _wfDocumentDownloadInput.url;

                if (_listadoDocs.Count > 0) 
                {
                    if (string.IsNullOrEmpty(_listadoDocs[0].result))
                        return View(_listadoDocs);

                    return RedirectToAction("Error", "Home", new { @statusCode = _listadoDocs[0].result.Split("|")[0], @message = _listadoDocs[0].result.Split("|")[1] });
                }
                return View(_listadoDocs);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home", new { @statusCode = 500, @message = ex.Message });
            }
        }

        // GET: Document/Create
        [SessionTimeout]
        public async Task<ActionResult> Create([FromQuery]string TipoSolicitud)
        {
            try
            {
                CrearDocumento crearDocumento = new CrearDocumento();

                ViewData["url_api_searchDocName"] = _ipInput.url_api_searchDocName;

                if (!string.IsNullOrEmpty(SessionState.Current.Session.GetString("full_name")))
                    crearDocumento.Solicitante = SessionState.Current.Session.GetString("full_name");

                if (!string.IsNullOrEmpty(SessionState.Current.Session.GetString("access_token")))
                    ViewData["jwt_access_token"] = SessionState.Current.Session.GetString("access_token");

                ViewData["uri_buscar_docsXtitulo"] = _wfDocumentSelectListDocsInput.url;

                // Departments {
                var _departamentos = await DepartmentsAsync();
                if (!string.IsNullOrEmpty(_departamentos[0].result))
                    return RedirectToAction("Error", "Home", new { @statusCode = _departamentos[0].result.Split("|")[0], @message = _departamentos[0].result.Split("|")[1] });

                if (!string.IsNullOrEmpty(SessionState.Current.Session.GetString("department")))
                {
                    ViewData["IdDepartamento"] = new SelectList(_departamentos, "CodigoDepartamento", "NombreDepartamento", SessionState.Current.Session.GetString("department"));
                }
                else
                {
                    ViewData["IdDepartamento"] = new SelectList(_departamentos, "CodigoDepartamento", "NombreDepartamento");
                }
                // ./Departments

                // DocumentaryTypologies {
                var _tipologias = await DocumentaryTypologiesAsync();
                if (!string.IsNullOrEmpty(_tipologias[0].result))

src/web/app-pms.web/Controllers/HomeController.cs
using System.Linq;
using System.Threading.Tasks;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using App_Pms.Web.Models;
using App_Pms.Web.Security;
using App_Pms.Web.DPWApiClient.Workflow.Entities;
using App_Pms.Web.DPWApiClient.Workflow.Entities.Input;
using App_Pms.Web.DPWApiClient.Workflow.Manager;
using System;
using Microsoft.AspNetCore.Authorization;

namespace App_Pms.Web.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        
        private readonly ILogger<HomeController> _logger;
        private readonly IPInput _ipInput;
        private readonly WFQueueInput _wfQueueInput;
        private readonly WFStatisticsInput _wfStatisticsInput;
        private readonly string _strIP;

        public HomeController(ILogger<HomeController> logger, IOptions<IPInput> ipInput, IOptions<WFQueueInput> wfQueueInput, IOptions<WFStatisticsInput> wfStatisticsInput)
        {   
            _logger = logger;
            _ipInput = ipInput.Value;
            _wfQueueInput = wfQueueInput.Value;
            _wfStatisticsInput = wfStatisticsInput.Value;
            
            _strIP = _ipInput.flag_url_dpw.Equals("0") ? _ipInput.url_dev : (_ipInput.flag_url_dpw.Equals("1") ? _ipInput.url_prd : string.Empty);

            _wfQueueInput.url = _wfQueueInput.url.Replace("{IP}", _strIP);
            _wfStatisticsInput.url = _wfStatisticsInput.url.Replace("{IP}", _strIP);
        }

        [SessionTimeout]
        public async Task<IActionResult> Index()
        {
            try
            {
                if ((!string.IsNullOrEmpty(SessionState.Current.Session.GetString("WFDocument"))) && (!SessionState.Current.Session.GetString("WFDocument").Equals("Error")))
                    ViewData["WFDocument"] = SessionState.Current.Session.GetString("WFDocument");

                HttpContext.Session.SetString("WFDocument", string.Empty);

                var statistics = await StatisticsBoardAsync(); var defaultValue = "TBD";
                if (!string.IsNullOrEmpty(statistics.result))
                    return RedirectToAction("Error", "Home", new { @statusCode = statistics.result.Split("|")[0], @message = statistics.result.Split("|")[1] });

                ViewData["CantidadCreacion"] = string.IsNullOrEmpty(statistics.CantidadCreacion) ? defaultValue : statistics.CantidadCreacion;
                ViewData["CantidadActualizacion"] = string.IsNullOrEmpty(statistics.CantidadActualizacion) ? defaultValue : statistics.CantidadActualizacion;
                ViewData["CantidadObsoletizacion"] = string.IsNullOrEmpty(statistics.CantidadObsoletizacion) ? defaultValue : statistics.CantidadObsoletizacion;
                ViewData["CantidadReactivacion"] = string.IsNullOrEmpty(statistics.CantidadReactivacion) ? defaultValue : statistics.CantidadReactivacion;
                ViewData["CantidadNomenclatura"] = string.IsNullOrEmpty(statistics.CantidadNomenclatura) ? defaultValue : statistics.CantidadNomenclatura;

                var _bandejaTrabajo = await WorkQueueAsync();

                if (_bandejaTrabajo == null)
                    return RedirectToAction("Error", "Home", new { @statusCode = 500, @message = "Error obteniendo la cola de trabajo." });
                
                if (string.IsNullOrEmpty(_bandejaTrabajo.result))
                    return View(_bandejaTrabajo.ListadoBandejaTrabajo.ToList());

                return RedirectToAction("Error", "Home", new { @statusCode = _bandejaTrabajo.result.Split("|")[0], @message = _bandejaTrabajo.result.Split("|")[1] });
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home", new { @statusCode = 500, @message = ex.Message });
            }
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error(int? statusCode = null, string message = "")
        {
            ErrorViewModel error = null;
            if (statusCode.HasValue)
            {
                error = new ErrorViewModel
                {
                    RequestId = statusCode.ToString(), RequestMessage = message
                };
            }
            return View(error);
        }

        private async Task<BandejaTrabajo> WorkQueueAsync()
        {   
            if (!string.IsNullOrEmpty(SessionState.Current.Session.GetString("access_token")))
                _wfQueueInput.access_token = SessionState.Current.Session.GetString("access_token");

            return await Common.GetWorkQueueAsync(_wfQueueInput);
        }

        private async Task<TableroEstadisticas> StatisticsBoardAsync()
        {
            if (!string.IsNullOrEmpty(SessionState.Current.Session.GetString("access_token")))
                _wfStatisticsInput.access_token = SessionState.Current.Session.GetString("access_token");

            return await Common.GetStatisticsBoardAsync(_wfStatisticsInput);
        }
    }
} 

src/web/app-pms.web/Views/Home/Index.cshtml
@model IEnumerable<App_Pms.Web.DPWApiClient.Workflow.Entities.ListadoBandejaTrabajo>
@{
    ViewData["Title"] = "Home Page";
}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Tablero de Control
            <small>Panel</small>
        </h1>
        <ol class="breadcrumb">
            <li><i class="fa fa-dashboard"></i> Inicio</li>
            <li class="active">Tablero de Control</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Alerts -->
        @{
            if (ViewData["WFDocument"] != null)
            {
                <div class="alert alert-success alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <h4><i class="icon fa fa-check"></i> Alerta!</h4>
                    @ViewData["WFDocument"]
                </div>
            }
        }
        <!-- /. Alerts -->
        <!-- Small boxes (Stat box) -->
        <div class="row">
            <div class="col-lg-3 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-aqua">
                    <div class="inner">
                        <h3>@ViewBag.CantidadCreacion</h3>

                        <p>Creación de Documentos</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-document"></i>
                    </div>
                    <a a asp-controller="Document" asp-action="Create" asp-route-TipoSolicitud="Creacion" class="small-box-footer">Iniciar Flujo Creación <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-2 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-green">
                    <div class="inner">
                        <h3>@ViewBag.CantidadActualizacion</h3>

                        <p>Modificación de Documentos</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-android-sync"></i>
                    </div>
                    <a asp-controller="Document" asp-action="Create" asp-route-TipoSolicitud="Actualizacion" class="small-box-footer">Iniciar Flujo Modificación <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-2 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-yellow">
                    <div class="inner">
                        <h3>@ViewBag.CantidadObsoletizacion</h3>

                        <p>Obsoletización de Documentos</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-power"></i>
                    </div>
                    <a asp-controller="Document" asp-action="Create" asp-route-TipoSolicitud="Obsoletizacion" class="small-box-footer">Iniciar Flujo Obsoletización <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-2 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-red">
                    <div class="inner">
                        <h3>@ViewBag.CantidadReactivacion</h3>

                        <p>Reactivación de Documentos</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-ios-fastforward"></i>
                    </div>
                    <a asp-controller="Document" asp-action="Create" asp-route-TipoSolicitud="Reactivacion" class="small-box-footer">Iniciar Flujo Reactivación <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-red">
                    <div class="inner">
                        <h3>@ViewBag.CantidadNomenclatura</h3>

                        <p>Cambio de Nomenclatura</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-ios-albums"></i>
                    </div>
                    <a asp-controller="Document" asp-action="Create" asp-route-TipoSolicitud="Nomenclatura" class="small-box-footer">Iniciar Flujo Cambio Nomenclatura <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->
        </div>
        <!-- /.row -->
        <!-- Main row -->
        <div class="row">
            <!-- section Left col -->
            <section class="col-lg-12 connectedSortable">
                <!-- col -->
                <div class="col-xs-12">
                    <!-- box -->
                    <div class="box">
                        <div class="box-header">
                            <h3 class="box-title">Cola de Trabajo - Documentos</h3>
                        </div>
                        <!-- datatable start -->
                        <div class="box-body">
                            <table id="example1" class="table table-bordered table-hover">
                                <thead>
                                    <tr>
                                        @*
                                            <th>ID</th>
                                            <th>Paso ID</th>
                                        *@
                                        <th>Tipo Solicitud</th>
                                        <th>Departamento</th>
                                        <th>Fecha</th>
                                        <th>Nombre Paso</th>
                                        <th>Requiere Soporte</th>
                                        <th>Nombre Documento</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            @*
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Id)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.IdPaso)
                                                </td>
                                            *@
                                            <td>
                                                @Html.DisplayFor(modelItem => item.TipoSolicitud)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Departamento)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Fecha)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.NombrePaso)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.RequiereSoporte)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.NombreDocumento)
                                            </td>
                                            <td>
                                                <a class="btn btn-info" role="button" asp-controller="Document" asp-action="Edit" asp-route-id="@item.Id" asp-route-idPaso="@item.IdPaso" asp-route-dDocName="@item.DocName" asp-route-dRevLabel="@item.NumeroRevisionDocumento" asp-route-dSecGroup="@item.GrupoSeguridad" asp-route-NombrePaso="@item.NombrePaso"><i class="fa fa-edit"></i></a>
                                                @*<button id="btnEdit" type="button" class="btn btn-info" data-valueId="@item.Id" data-valueIdPaso="@item.IdPaso" data-toggle="modal" data-target="#modal-default"><i class="fa fa-edit"></i></button>*@
                                                @*<a href="#" id="btnEditar" class="btn btn-info" data-valueId="@item.Id" data-valueIdPaso="@item.IdPaso"><i class="fa fa-edit"></i></a>*@
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                        <!-- datatable end -->
                        <!-- modal start -->
                        <div class="modal fade" id="modal-default">
                            <!-- modal-dialog -->
                            <div class="modal-dialog">
                                <!-- modal-content -->
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                        <h4 class="modal-title">Editar Documentos / []</h4>
                                    </div>
                                    <div class="modal-body">
                                        <!-- form start -->
                                        <form role="form">
                                            <!--box-body -->
                                            <div class="box-body">
                                                <div id="ContentModalEdit">
                                                </div>
                                            </div>
                                            <!-- /.box-body -->
                                        </form>
                                        <!-- /form start -->
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Cerrar</button>
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Aprobar</button>
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Descargar</button>
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Rechazar</button>
                                    </div>
                                </div>
                                <!-- /.modal-content -->
                            </div>
                            <!-- /.modal-dialog -->
                        </div>
                        <!-- /.modal end -->

                    </div>
                    <!-- /.box -->
                </div>
                <!-- /.col -->
            </section>
            <!-- /.section Left col -->
        </div>
        <!-- /.row (Main row) -->
    </section>
    <!-- /. Main content -->
</div>
<!-- /.content-wrapper -->


@section Scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            $("#btnEdit").click(function () {
                var id = $(this).data("valueId");
                var idPaso = $(this).data("valueIdPaso");
                $("#ContentModalEdit").load("/Document/Edit/" + id + "?idPaso=" + idPaso,
                    function () {
                        $("#modal-default").modal("show");
                    }
                );
            });
        });
    </script>
}